targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/blocs/*/**.dart
            - lib/models/**.dart
        options:
          # You can customize freezed options here if needed
          copy_with: true
          equal: true
          to_string: true
      json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false
